name: run
run_id: commands[0]
env TERM: xterm-256color
env TMPDIR: /var/folders/6_/vjwf9w3d1q7798qtl6gm3bqh0000gn/T/
env LANG: en_US.UTF-8
env HOME: /Users/anisha
env PATH: /Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Users/anisha/Documents/Dev/Apache-Spark/spark-3.5.0-bin-hadoop3/bin
env PYTHONHASHSEED: 3344257276
env PIP_DISABLE_PIP_VERSION_CHECK: 1
env PYTHONIOENCODING: utf-8
env PYTHONPATH: .
env TOX_ENV_NAME: run
env TOX_WORK_DIR: /Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox
env TOX_ENV_DIR: /Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app
env VIRTUAL_ENV: /Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app
env COLUMNS: 190
env LINES: 15
metadata pid: 81563
cwd: /Users/anisha/Documents/GitHub/mlops-regression/prediction-app
allow: /Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/bin/*
cmd: python app/main.py
exit_code: -2
[32mINFO[0m:     ::1:55865 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:55865 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:55865 - "[1mGET /api/v1/openapi.json HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:55867 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:55867 - "[1mGET /docs HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:55867 - "[1mGET /api/v1/openapi.json HTTP/1.1[0m" [32m200 OK[0m
[32mINFO[0m:     ::1:55874 - "[1mGET / HTTP/1.1[0m" [32m200 OK[0m

standard error:
[32m2024-06-11 21:00:36.479[0m | [33m[1mWARNING [0m | [36m__main__[0m:[36m<module>[0m:[36m55[0m - [33m[1mRunning in development mode. Do not run like this in production.[0m
[32mINFO[0m:     Started server process [[36m81563[0m]
[32mINFO[0m:     Waiting for application startup.
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://localhost:8001[0m (Press CTRL+C to quit)
[32mINFO[0m:     Shutting down
[32mINFO[0m:     Finished server process [[36m81563[0m]
[31mERROR[0m:    Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/starlette/routing.py", line 741, in lifespan
    await receive()
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "app/main.py", line 58, in <module>
    uvicorn.run(app, host="localhost", port=8001, log_level="debug")
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1511, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1504, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1377, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 555, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 474, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 83, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/Users/anisha/Documents/GitHub/mlops-regression/prediction-app/.tox/test_app/lib/python3.8/site-packages/uvicorn/server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
